version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    env_file:
      - ./config/mysql.env
    command: [ '--default-authentication-plugin=mysql_native_password' ]
    restart: always
    networks:
      - metabase-mysql
  metabase:
    image: metabase/metabase
    env_file:
      - ./config/metabase.env
    networks:
      - metabase-mysql
    depends_on:
      - mysql
    ports:
      - "3000:3000"

networks:
  metabase-mysql:
    driver: bridge
